#!/usr/bin/env php
<?php

use App\Console\Kernel;
use Illuminate\Console\Application as Artisan;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;

require __DIR__.'/bootstrap/autoload.php';

$app = require __DIR__.'/bootstrap/app.php';

$bootstrappers = [
    'Illuminate\Foundation\Bootstrap\DetectEnvironment',
    'Illuminate\Foundation\Bootstrap\LoadConfiguration',
    'Illuminate\Foundation\Bootstrap\ConfigureLogging',
    'Illuminate\Foundation\Bootstrap\HandleExceptions',
    'Illuminate\Foundation\Bootstrap\RegisterFacades',
    'Illuminate\Foundation\Bootstrap\SetRequestForConsole',
    'Illuminate\Foundation\Bootstrap\RegisterProviders',
    'Illuminate\Foundation\Bootstrap\BootProviders',
];

if (! $app->hasBeenBootstrapped()) {
    $app->bootstrapWith($bootstrappers);
}

$kernel = $app->make(Kernel::class);

$artisan = (new Artisan($app, $app->make('events'), '0.1'));

$artisan->setName('Surveil Console');

$artisan->resolveCommands($kernel->listCommands());

$artisan->run(new ArgvInput, new ConsoleOutput);
