#!/usr/bin/env php
<?php

use App\Console\Kernel;
use Illuminate\Console\Application as Artisan;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;

require __DIR__.'/bootstrap/autoload.php';

$app = require __DIR__.'/bootstrap/app.php';


$kernel = $app->make(Kernel::class);

$artisan = (new Artisan($app, $app->make('events'), '0.1'));

$artisan->setName('Surveil Console');

$artisan->resolveCommands($kernel->listCommands());

$artisan->run(new ArgvInput, new ConsoleOutput);
